//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormDesignFSS2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49220/NguoiDungBUS.asmx")]
        public string FormDesignFSS2_NguoiDungWS_NguoiDungBUS {
            get {
                return ((string)(this["FormDesignFSS2_NguoiDungWS_NguoiDungBUS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49220/KhachHangBUS.asmx")]
        public string FormDesignFSS2_KhachHangWS_KhachHangBUS {
            get {
                return ((string)(this["FormDesignFSS2_KhachHangWS_KhachHangBUS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49220/NguonBUS.asmx")]
        public string FormDesignFSS2_NguonWS_NguonBUS {
            get {
                return ((string)(this["FormDesignFSS2_NguonWS_NguonBUS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49220/SanPhamTinDungBUS.asmx")]
        public string FormDesignFSS2_SanPhamTinDungWS_SanPhamTinDungBUS {
            get {
                return ((string)(this["FormDesignFSS2_SanPhamTinDungWS_SanPhamTinDungBUS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49220/KhachHang_SPTD_BUS.asmx")]
        public string FormDesignFSS2_KhachHang_SPTD_WS_KhachHang_SPTD_BUS {
            get {
                return ((string)(this["FormDesignFSS2_KhachHang_SPTD_WS_KhachHang_SPTD_BUS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49220/GiaiNganBUS.asmx")]
        public string FormDesignFSS2_GiaiNganWS_GiaiNganBUS
        {
            get
            {
                return ((string)(this["FormDesignFSS2_GiaiNganWS_GiaiNganBUS"]));
            }
        }

        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:49220/XuLyCuoiNgayBUS.asmx")]
        public string FormDesignFSS2_XuLyCuoiNgayWS_XuLyCuoiNgayBUS
        {
            get
            {
                return ((string)(this["FormDesignFSS2_XuLyCuoiNgayWS_XuLyCuoiNgayBUS"]));
            }
        }
            }
        }
    


