//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FormDesignFSS2.NguoiDungWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NguoiDungBUSSoap", Namespace="http://tempuri.org/")]
    public partial class NguoiDungBUS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback KTThongTinDangNhapOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNguoiDungOperationCompleted;
        
        private System.Threading.SendOrPostCallback KTThongTinThemNguoiDungOperationCompleted;
        
        private System.Threading.SendOrPostCallback LayDSNguoiDungOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NguoiDungBUS() {
            this.Url = global::FormDesignFSS2.Properties.Settings.Default.FormDesignFSS2_NguoiDungWS_NguoiDungBUS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event KTThongTinDangNhapCompletedEventHandler KTThongTinDangNhapCompleted;
        
        /// <remarks/>
        public event GetNguoiDungCompletedEventHandler GetNguoiDungCompleted;
        
        /// <remarks/>
        public event KTThongTinThemNguoiDungCompletedEventHandler KTThongTinThemNguoiDungCompleted;
        
        /// <remarks/>
        public event LayDSNguoiDungCompletedEventHandler LayDSNguoiDungCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KTThongTinDangNhap", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int KTThongTinDangNhap(string tenDangNhap, string matKhau) {
            object[] results = this.Invoke("KTThongTinDangNhap", new object[] {
                        tenDangNhap,
                        matKhau});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void KTThongTinDangNhapAsync(string tenDangNhap, string matKhau) {
            this.KTThongTinDangNhapAsync(tenDangNhap, matKhau, null);
        }
        
        /// <remarks/>
        public void KTThongTinDangNhapAsync(string tenDangNhap, string matKhau, object userState) {
            if ((this.KTThongTinDangNhapOperationCompleted == null)) {
                this.KTThongTinDangNhapOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKTThongTinDangNhapOperationCompleted);
            }
            this.InvokeAsync("KTThongTinDangNhap", new object[] {
                        tenDangNhap,
                        matKhau}, this.KTThongTinDangNhapOperationCompleted, userState);
        }
        
        private void OnKTThongTinDangNhapOperationCompleted(object arg) {
            if ((this.KTThongTinDangNhapCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KTThongTinDangNhapCompleted(this, new KTThongTinDangNhapCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNguoiDung", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetNguoiDung(string tenDangNhap, string matKhau) {
            object[] results = this.Invoke("GetNguoiDung", new object[] {
                        tenDangNhap,
                        matKhau});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetNguoiDungAsync(string tenDangNhap, string matKhau) {
            this.GetNguoiDungAsync(tenDangNhap, matKhau, null);
        }
        
        /// <remarks/>
        public void GetNguoiDungAsync(string tenDangNhap, string matKhau, object userState) {
            if ((this.GetNguoiDungOperationCompleted == null)) {
                this.GetNguoiDungOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNguoiDungOperationCompleted);
            }
            this.InvokeAsync("GetNguoiDung", new object[] {
                        tenDangNhap,
                        matKhau}, this.GetNguoiDungOperationCompleted, userState);
        }
        
        private void OnGetNguoiDungOperationCompleted(object arg) {
            if ((this.GetNguoiDungCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNguoiDungCompleted(this, new GetNguoiDungCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KTThongTinThemNguoiDung", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int KTThongTinThemNguoiDung(string hoTen, string chucVu, string phongBan, string quyen) {
            object[] results = this.Invoke("KTThongTinThemNguoiDung", new object[] {
                        hoTen,
                        chucVu,
                        phongBan,
                        quyen});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void KTThongTinThemNguoiDungAsync(string hoTen, string chucVu, string phongBan, string quyen) {
            this.KTThongTinThemNguoiDungAsync(hoTen, chucVu, phongBan, quyen, null);
        }
        
        /// <remarks/>
        public void KTThongTinThemNguoiDungAsync(string hoTen, string chucVu, string phongBan, string quyen, object userState) {
            if ((this.KTThongTinThemNguoiDungOperationCompleted == null)) {
                this.KTThongTinThemNguoiDungOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKTThongTinThemNguoiDungOperationCompleted);
            }
            this.InvokeAsync("KTThongTinThemNguoiDung", new object[] {
                        hoTen,
                        chucVu,
                        phongBan,
                        quyen}, this.KTThongTinThemNguoiDungOperationCompleted, userState);
        }
        
        private void OnKTThongTinThemNguoiDungOperationCompleted(object arg) {
            if ((this.KTThongTinThemNguoiDungCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KTThongTinThemNguoiDungCompleted(this, new KTThongTinThemNguoiDungCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayDSNguoiDung", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LayDSNguoiDung() {
            object[] results = this.Invoke("LayDSNguoiDung", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LayDSNguoiDungAsync() {
            this.LayDSNguoiDungAsync(null);
        }
        
        /// <remarks/>
        public void LayDSNguoiDungAsync(object userState) {
            if ((this.LayDSNguoiDungOperationCompleted == null)) {
                this.LayDSNguoiDungOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLayDSNguoiDungOperationCompleted);
            }
            this.InvokeAsync("LayDSNguoiDung", new object[0], this.LayDSNguoiDungOperationCompleted, userState);
        }
        
        private void OnLayDSNguoiDungOperationCompleted(object arg) {
            if ((this.LayDSNguoiDungCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LayDSNguoiDungCompleted(this, new LayDSNguoiDungCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void KTThongTinDangNhapCompletedEventHandler(object sender, KTThongTinDangNhapCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KTThongTinDangNhapCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KTThongTinDangNhapCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetNguoiDungCompletedEventHandler(object sender, GetNguoiDungCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNguoiDungCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNguoiDungCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void KTThongTinThemNguoiDungCompletedEventHandler(object sender, KTThongTinThemNguoiDungCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KTThongTinThemNguoiDungCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KTThongTinThemNguoiDungCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void LayDSNguoiDungCompletedEventHandler(object sender, LayDSNguoiDungCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LayDSNguoiDungCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LayDSNguoiDungCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591