//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FormDesignFSS2.KhachHangWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="KhachHangBUSSoap", Namespace="http://tempuri.org/")]
    public partial class KhachHangBUS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback KTThongTinThemKHOperationCompleted;
        
        private System.Threading.SendOrPostCallback KTThongTinSuaKHOperationCompleted;
        
        private System.Threading.SendOrPostCallback layDSKhachHangOperationCompleted;
        
        private System.Threading.SendOrPostCallback layMotKhachHangOperationCompleted;
        
        private System.Threading.SendOrPostCallback TimKiemKHOperationCompleted;
        
        private System.Threading.SendOrPostCallback suaThongTinKHOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThemKHOperationCompleted;
        
        private System.Threading.SendOrPostCallback KhachHangReportOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public KhachHangBUS() {
            this.Url = global::FormDesignFSS2.Properties.Settings.Default.FormDesignFSS2_KhachHangWS_KhachHangBUS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event KTThongTinThemKHCompletedEventHandler KTThongTinThemKHCompleted;
        
        /// <remarks/>
        public event KTThongTinSuaKHCompletedEventHandler KTThongTinSuaKHCompleted;
        
        /// <remarks/>
        public event layDSKhachHangCompletedEventHandler layDSKhachHangCompleted;
        
        /// <remarks/>
        public event layMotKhachHangCompletedEventHandler layMotKhachHangCompleted;
        
        /// <remarks/>
        public event TimKiemKHCompletedEventHandler TimKiemKHCompleted;
        
        /// <remarks/>
        public event suaThongTinKHCompletedEventHandler suaThongTinKHCompleted;
        
        /// <remarks/>
        public event ThemKHCompletedEventHandler ThemKHCompleted;
        
        /// <remarks/>
        public event KhachHangReportCompletedEventHandler KhachHangReportCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KTThongTinThemKH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int KTThongTinThemKH(string soTKLK, System.DateTime ngayMoTK, string hoTen, System.DateTime ngaySinh, string ngheNghiep, string soCMND, string diaChi, string email, string SDT) {
            object[] results = this.Invoke("KTThongTinThemKH", new object[] {
                        soTKLK,
                        ngayMoTK,
                        hoTen,
                        ngaySinh,
                        ngheNghiep,
                        soCMND,
                        diaChi,
                        email,
                        SDT});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void KTThongTinThemKHAsync(string soTKLK, System.DateTime ngayMoTK, string hoTen, System.DateTime ngaySinh, string ngheNghiep, string soCMND, string diaChi, string email, string SDT) {
            this.KTThongTinThemKHAsync(soTKLK, ngayMoTK, hoTen, ngaySinh, ngheNghiep, soCMND, diaChi, email, SDT, null);
        }
        
        /// <remarks/>
        public void KTThongTinThemKHAsync(string soTKLK, System.DateTime ngayMoTK, string hoTen, System.DateTime ngaySinh, string ngheNghiep, string soCMND, string diaChi, string email, string SDT, object userState) {
            if ((this.KTThongTinThemKHOperationCompleted == null)) {
                this.KTThongTinThemKHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKTThongTinThemKHOperationCompleted);
            }
            this.InvokeAsync("KTThongTinThemKH", new object[] {
                        soTKLK,
                        ngayMoTK,
                        hoTen,
                        ngaySinh,
                        ngheNghiep,
                        soCMND,
                        diaChi,
                        email,
                        SDT}, this.KTThongTinThemKHOperationCompleted, userState);
        }
        
        private void OnKTThongTinThemKHOperationCompleted(object arg) {
            if ((this.KTThongTinThemKHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KTThongTinThemKHCompleted(this, new KTThongTinThemKHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KTThongTinSuaKH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int KTThongTinSuaKH(System.DateTime ngayMoTK, string hoTenKH, System.DateTime ngaySinh, string ngheNghiep, string soCMND, string diaChi, string email, string sdt) {
            object[] results = this.Invoke("KTThongTinSuaKH", new object[] {
                        ngayMoTK,
                        hoTenKH,
                        ngaySinh,
                        ngheNghiep,
                        soCMND,
                        diaChi,
                        email,
                        sdt});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void KTThongTinSuaKHAsync(System.DateTime ngayMoTK, string hoTenKH, System.DateTime ngaySinh, string ngheNghiep, string soCMND, string diaChi, string email, string sdt) {
            this.KTThongTinSuaKHAsync(ngayMoTK, hoTenKH, ngaySinh, ngheNghiep, soCMND, diaChi, email, sdt, null);
        }
        
        /// <remarks/>
        public void KTThongTinSuaKHAsync(System.DateTime ngayMoTK, string hoTenKH, System.DateTime ngaySinh, string ngheNghiep, string soCMND, string diaChi, string email, string sdt, object userState) {
            if ((this.KTThongTinSuaKHOperationCompleted == null)) {
                this.KTThongTinSuaKHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKTThongTinSuaKHOperationCompleted);
            }
            this.InvokeAsync("KTThongTinSuaKH", new object[] {
                        ngayMoTK,
                        hoTenKH,
                        ngaySinh,
                        ngheNghiep,
                        soCMND,
                        diaChi,
                        email,
                        sdt}, this.KTThongTinSuaKHOperationCompleted, userState);
        }
        
        private void OnKTThongTinSuaKHOperationCompleted(object arg) {
            if ((this.KTThongTinSuaKHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KTThongTinSuaKHCompleted(this, new KTThongTinSuaKHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/layDSKhachHang", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string layDSKhachHang() {
            object[] results = this.Invoke("layDSKhachHang", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void layDSKhachHangAsync() {
            this.layDSKhachHangAsync(null);
        }
        
        /// <remarks/>
        public void layDSKhachHangAsync(object userState) {
            if ((this.layDSKhachHangOperationCompleted == null)) {
                this.layDSKhachHangOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlayDSKhachHangOperationCompleted);
            }
            this.InvokeAsync("layDSKhachHang", new object[0], this.layDSKhachHangOperationCompleted, userState);
        }
        
        private void OnlayDSKhachHangOperationCompleted(object arg) {
            if ((this.layDSKhachHangCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.layDSKhachHangCompleted(this, new layDSKhachHangCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/layMotKhachHang", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string layMotKhachHang(string soTKLK) {
            object[] results = this.Invoke("layMotKhachHang", new object[] {
                        soTKLK});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void layMotKhachHangAsync(string soTKLK) {
            this.layMotKhachHangAsync(soTKLK, null);
        }
        
        /// <remarks/>
        public void layMotKhachHangAsync(string soTKLK, object userState) {
            if ((this.layMotKhachHangOperationCompleted == null)) {
                this.layMotKhachHangOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlayMotKhachHangOperationCompleted);
            }
            this.InvokeAsync("layMotKhachHang", new object[] {
                        soTKLK}, this.layMotKhachHangOperationCompleted, userState);
        }
        
        private void OnlayMotKhachHangOperationCompleted(object arg) {
            if ((this.layMotKhachHangCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.layMotKhachHangCompleted(this, new layMotKhachHangCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimKiemKH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TimKiemKH(string soTKLK, string hoTenKH, string soCMND) {
            object[] results = this.Invoke("TimKiemKH", new object[] {
                        soTKLK,
                        hoTenKH,
                        soCMND});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TimKiemKHAsync(string soTKLK, string hoTenKH, string soCMND) {
            this.TimKiemKHAsync(soTKLK, hoTenKH, soCMND, null);
        }
        
        /// <remarks/>
        public void TimKiemKHAsync(string soTKLK, string hoTenKH, string soCMND, object userState) {
            if ((this.TimKiemKHOperationCompleted == null)) {
                this.TimKiemKHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimKiemKHOperationCompleted);
            }
            this.InvokeAsync("TimKiemKH", new object[] {
                        soTKLK,
                        hoTenKH,
                        soCMND}, this.TimKiemKHOperationCompleted, userState);
        }
        
        private void OnTimKiemKHOperationCompleted(object arg) {
            if ((this.TimKiemKHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TimKiemKHCompleted(this, new TimKiemKHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/suaThongTinKH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool suaThongTinKH(string soTKLK, string hoTenKH, string loaiKH, System.DateTime ngaySinhKH, string gioiTinhKH, string ngheNghiep, string soCMND, string diaChiKH, string emailKH, string SDT, string ghiChu) {
            object[] results = this.Invoke("suaThongTinKH", new object[] {
                        soTKLK,
                        hoTenKH,
                        loaiKH,
                        ngaySinhKH,
                        gioiTinhKH,
                        ngheNghiep,
                        soCMND,
                        diaChiKH,
                        emailKH,
                        SDT,
                        ghiChu});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void suaThongTinKHAsync(string soTKLK, string hoTenKH, string loaiKH, System.DateTime ngaySinhKH, string gioiTinhKH, string ngheNghiep, string soCMND, string diaChiKH, string emailKH, string SDT, string ghiChu) {
            this.suaThongTinKHAsync(soTKLK, hoTenKH, loaiKH, ngaySinhKH, gioiTinhKH, ngheNghiep, soCMND, diaChiKH, emailKH, SDT, ghiChu, null);
        }
        
        /// <remarks/>
        public void suaThongTinKHAsync(string soTKLK, string hoTenKH, string loaiKH, System.DateTime ngaySinhKH, string gioiTinhKH, string ngheNghiep, string soCMND, string diaChiKH, string emailKH, string SDT, string ghiChu, object userState) {
            if ((this.suaThongTinKHOperationCompleted == null)) {
                this.suaThongTinKHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsuaThongTinKHOperationCompleted);
            }
            this.InvokeAsync("suaThongTinKH", new object[] {
                        soTKLK,
                        hoTenKH,
                        loaiKH,
                        ngaySinhKH,
                        gioiTinhKH,
                        ngheNghiep,
                        soCMND,
                        diaChiKH,
                        emailKH,
                        SDT,
                        ghiChu}, this.suaThongTinKHOperationCompleted, userState);
        }
        
        private void OnsuaThongTinKHOperationCompleted(object arg) {
            if ((this.suaThongTinKHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.suaThongTinKHCompleted(this, new suaThongTinKHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThemKH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ThemKH(string jsonData) {
            object[] results = this.Invoke("ThemKH", new object[] {
                        jsonData});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ThemKHAsync(string jsonData) {
            this.ThemKHAsync(jsonData, null);
        }
        
        /// <remarks/>
        public void ThemKHAsync(string jsonData, object userState) {
            if ((this.ThemKHOperationCompleted == null)) {
                this.ThemKHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThemKHOperationCompleted);
            }
            this.InvokeAsync("ThemKH", new object[] {
                        jsonData}, this.ThemKHOperationCompleted, userState);
        }
        
        private void OnThemKHOperationCompleted(object arg) {
            if ((this.ThemKHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThemKHCompleted(this, new ThemKHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KhachHangReport", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string KhachHangReport() {
            object[] results = this.Invoke("KhachHangReport", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void KhachHangReportAsync() {
            this.KhachHangReportAsync(null);
        }
        
        /// <remarks/>
        public void KhachHangReportAsync(object userState) {
            if ((this.KhachHangReportOperationCompleted == null)) {
                this.KhachHangReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKhachHangReportOperationCompleted);
            }
            this.InvokeAsync("KhachHangReport", new object[0], this.KhachHangReportOperationCompleted, userState);
        }
        
        private void OnKhachHangReportOperationCompleted(object arg) {
            if ((this.KhachHangReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KhachHangReportCompleted(this, new KhachHangReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void KTThongTinThemKHCompletedEventHandler(object sender, KTThongTinThemKHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KTThongTinThemKHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KTThongTinThemKHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void KTThongTinSuaKHCompletedEventHandler(object sender, KTThongTinSuaKHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KTThongTinSuaKHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KTThongTinSuaKHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void layDSKhachHangCompletedEventHandler(object sender, layDSKhachHangCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class layDSKhachHangCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal layDSKhachHangCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void layMotKhachHangCompletedEventHandler(object sender, layMotKhachHangCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class layMotKhachHangCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal layMotKhachHangCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TimKiemKHCompletedEventHandler(object sender, TimKiemKHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimKiemKHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TimKiemKHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void suaThongTinKHCompletedEventHandler(object sender, suaThongTinKHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class suaThongTinKHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal suaThongTinKHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ThemKHCompletedEventHandler(object sender, ThemKHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThemKHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThemKHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void KhachHangReportCompletedEventHandler(object sender, KhachHangReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KhachHangReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KhachHangReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591