//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FormDesignFSS2.ReportWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ReportBUSSoap", Namespace="http://tempuri.org/")]
    public partial class ReportBUS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetListDSDuNoAOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListDSDuNoBOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListDSDuNoCOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListDSKHHetNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListDSDuNoEOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListDSSPTDAOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListDSSPTDBOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListDSGNAOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListDSGNBOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListDSNguonAOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ReportBUS() {
            this.Url = global::FormDesignFSS2.Properties.Settings.Default.QLTD_ReportWS_ReportBUS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetListDSDuNoACompletedEventHandler GetListDSDuNoACompleted;
        
        /// <remarks/>
        public event GetListDSDuNoBCompletedEventHandler GetListDSDuNoBCompleted;
        
        /// <remarks/>
        public event GetListDSDuNoCCompletedEventHandler GetListDSDuNoCCompleted;
        
        /// <remarks/>
        public event GetListDSKHHetNoCompletedEventHandler GetListDSKHHetNoCompleted;
        
        /// <remarks/>
        public event GetListDSDuNoECompletedEventHandler GetListDSDuNoECompleted;
        
        /// <remarks/>
        public event GetListDSSPTDACompletedEventHandler GetListDSSPTDACompleted;
        
        /// <remarks/>
        public event GetListDSSPTDBCompletedEventHandler GetListDSSPTDBCompleted;
        
        /// <remarks/>
        public event GetListDSGNACompletedEventHandler GetListDSGNACompleted;
        
        /// <remarks/>
        public event GetListDSGNBCompletedEventHandler GetListDSGNBCompleted;
        
        /// <remarks/>
        public event GetListDSNguonACompletedEventHandler GetListDSNguonACompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListDSDuNoA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetListDSDuNoA(string ngayHT) {
            object[] results = this.Invoke("GetListDSDuNoA", new object[] {
                        ngayHT});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetListDSDuNoAAsync(string ngayHT) {
            this.GetListDSDuNoAAsync(ngayHT, null);
        }
        
        /// <remarks/>
        public void GetListDSDuNoAAsync(string ngayHT, object userState) {
            if ((this.GetListDSDuNoAOperationCompleted == null)) {
                this.GetListDSDuNoAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListDSDuNoAOperationCompleted);
            }
            this.InvokeAsync("GetListDSDuNoA", new object[] {
                        ngayHT}, this.GetListDSDuNoAOperationCompleted, userState);
        }
        
        private void OnGetListDSDuNoAOperationCompleted(object arg) {
            if ((this.GetListDSDuNoACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListDSDuNoACompleted(this, new GetListDSDuNoACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListDSDuNoB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetListDSDuNoB() {
            object[] results = this.Invoke("GetListDSDuNoB", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetListDSDuNoBAsync() {
            this.GetListDSDuNoBAsync(null);
        }
        
        /// <remarks/>
        public void GetListDSDuNoBAsync(object userState) {
            if ((this.GetListDSDuNoBOperationCompleted == null)) {
                this.GetListDSDuNoBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListDSDuNoBOperationCompleted);
            }
            this.InvokeAsync("GetListDSDuNoB", new object[0], this.GetListDSDuNoBOperationCompleted, userState);
        }
        
        private void OnGetListDSDuNoBOperationCompleted(object arg) {
            if ((this.GetListDSDuNoBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListDSDuNoBCompleted(this, new GetListDSDuNoBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListDSDuNoC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetListDSDuNoC(string ngayHT) {
            object[] results = this.Invoke("GetListDSDuNoC", new object[] {
                        ngayHT});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetListDSDuNoCAsync(string ngayHT) {
            this.GetListDSDuNoCAsync(ngayHT, null);
        }
        
        /// <remarks/>
        public void GetListDSDuNoCAsync(string ngayHT, object userState) {
            if ((this.GetListDSDuNoCOperationCompleted == null)) {
                this.GetListDSDuNoCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListDSDuNoCOperationCompleted);
            }
            this.InvokeAsync("GetListDSDuNoC", new object[] {
                        ngayHT}, this.GetListDSDuNoCOperationCompleted, userState);
        }
        
        private void OnGetListDSDuNoCOperationCompleted(object arg) {
            if ((this.GetListDSDuNoCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListDSDuNoCCompleted(this, new GetListDSDuNoCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListDSKHHetNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetListDSKHHetNo() {
            object[] results = this.Invoke("GetListDSKHHetNo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetListDSKHHetNoAsync() {
            this.GetListDSKHHetNoAsync(null);
        }
        
        /// <remarks/>
        public void GetListDSKHHetNoAsync(object userState) {
            if ((this.GetListDSKHHetNoOperationCompleted == null)) {
                this.GetListDSKHHetNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListDSKHHetNoOperationCompleted);
            }
            this.InvokeAsync("GetListDSKHHetNo", new object[0], this.GetListDSKHHetNoOperationCompleted, userState);
        }
        
        private void OnGetListDSKHHetNoOperationCompleted(object arg) {
            if ((this.GetListDSKHHetNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListDSKHHetNoCompleted(this, new GetListDSKHHetNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListDSDuNoE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetListDSDuNoE() {
            object[] results = this.Invoke("GetListDSDuNoE", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetListDSDuNoEAsync() {
            this.GetListDSDuNoEAsync(null);
        }
        
        /// <remarks/>
        public void GetListDSDuNoEAsync(object userState) {
            if ((this.GetListDSDuNoEOperationCompleted == null)) {
                this.GetListDSDuNoEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListDSDuNoEOperationCompleted);
            }
            this.InvokeAsync("GetListDSDuNoE", new object[0], this.GetListDSDuNoEOperationCompleted, userState);
        }
        
        private void OnGetListDSDuNoEOperationCompleted(object arg) {
            if ((this.GetListDSDuNoECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListDSDuNoECompleted(this, new GetListDSDuNoECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListDSSPTDA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetListDSSPTDA() {
            object[] results = this.Invoke("GetListDSSPTDA", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetListDSSPTDAAsync() {
            this.GetListDSSPTDAAsync(null);
        }
        
        /// <remarks/>
        public void GetListDSSPTDAAsync(object userState) {
            if ((this.GetListDSSPTDAOperationCompleted == null)) {
                this.GetListDSSPTDAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListDSSPTDAOperationCompleted);
            }
            this.InvokeAsync("GetListDSSPTDA", new object[0], this.GetListDSSPTDAOperationCompleted, userState);
        }
        
        private void OnGetListDSSPTDAOperationCompleted(object arg) {
            if ((this.GetListDSSPTDACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListDSSPTDACompleted(this, new GetListDSSPTDACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListDSSPTDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetListDSSPTDB() {
            object[] results = this.Invoke("GetListDSSPTDB", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetListDSSPTDBAsync() {
            this.GetListDSSPTDBAsync(null);
        }
        
        /// <remarks/>
        public void GetListDSSPTDBAsync(object userState) {
            if ((this.GetListDSSPTDBOperationCompleted == null)) {
                this.GetListDSSPTDBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListDSSPTDBOperationCompleted);
            }
            this.InvokeAsync("GetListDSSPTDB", new object[0], this.GetListDSSPTDBOperationCompleted, userState);
        }
        
        private void OnGetListDSSPTDBOperationCompleted(object arg) {
            if ((this.GetListDSSPTDBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListDSSPTDBCompleted(this, new GetListDSSPTDBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListDSGNA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetListDSGNA(string gioHT) {
            object[] results = this.Invoke("GetListDSGNA", new object[] {
                        gioHT});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetListDSGNAAsync(string gioHT) {
            this.GetListDSGNAAsync(gioHT, null);
        }
        
        /// <remarks/>
        public void GetListDSGNAAsync(string gioHT, object userState) {
            if ((this.GetListDSGNAOperationCompleted == null)) {
                this.GetListDSGNAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListDSGNAOperationCompleted);
            }
            this.InvokeAsync("GetListDSGNA", new object[] {
                        gioHT}, this.GetListDSGNAOperationCompleted, userState);
        }
        
        private void OnGetListDSGNAOperationCompleted(object arg) {
            if ((this.GetListDSGNACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListDSGNACompleted(this, new GetListDSGNACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListDSGNB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetListDSGNB() {
            object[] results = this.Invoke("GetListDSGNB", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetListDSGNBAsync() {
            this.GetListDSGNBAsync(null);
        }
        
        /// <remarks/>
        public void GetListDSGNBAsync(object userState) {
            if ((this.GetListDSGNBOperationCompleted == null)) {
                this.GetListDSGNBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListDSGNBOperationCompleted);
            }
            this.InvokeAsync("GetListDSGNB", new object[0], this.GetListDSGNBOperationCompleted, userState);
        }
        
        private void OnGetListDSGNBOperationCompleted(object arg) {
            if ((this.GetListDSGNBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListDSGNBCompleted(this, new GetListDSGNBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListDSNguonA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetListDSNguonA() {
            object[] results = this.Invoke("GetListDSNguonA", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetListDSNguonAAsync() {
            this.GetListDSNguonAAsync(null);
        }
        
        /// <remarks/>
        public void GetListDSNguonAAsync(object userState) {
            if ((this.GetListDSNguonAOperationCompleted == null)) {
                this.GetListDSNguonAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListDSNguonAOperationCompleted);
            }
            this.InvokeAsync("GetListDSNguonA", new object[0], this.GetListDSNguonAOperationCompleted, userState);
        }
        
        private void OnGetListDSNguonAOperationCompleted(object arg) {
            if ((this.GetListDSNguonACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListDSNguonACompleted(this, new GetListDSNguonACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetListDSDuNoACompletedEventHandler(object sender, GetListDSDuNoACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListDSDuNoACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListDSDuNoACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetListDSDuNoBCompletedEventHandler(object sender, GetListDSDuNoBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListDSDuNoBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListDSDuNoBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetListDSDuNoCCompletedEventHandler(object sender, GetListDSDuNoCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListDSDuNoCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListDSDuNoCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetListDSKHHetNoCompletedEventHandler(object sender, GetListDSKHHetNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListDSKHHetNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListDSKHHetNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetListDSDuNoECompletedEventHandler(object sender, GetListDSDuNoECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListDSDuNoECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListDSDuNoECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetListDSSPTDACompletedEventHandler(object sender, GetListDSSPTDACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListDSSPTDACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListDSSPTDACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetListDSSPTDBCompletedEventHandler(object sender, GetListDSSPTDBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListDSSPTDBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListDSSPTDBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetListDSGNACompletedEventHandler(object sender, GetListDSGNACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListDSGNACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListDSGNACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetListDSGNBCompletedEventHandler(object sender, GetListDSGNBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListDSGNBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListDSGNBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetListDSNguonACompletedEventHandler(object sender, GetListDSNguonACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListDSNguonACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListDSNguonACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591